---
# The hooks are run every time a ` git commit -m "blah" ` is run.
# Usage instructions:

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
# Run pylint and black locally otherwise there's annoying import errors and it tries to docstring things that @click cannot docstring
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint --disable=R,C
        language: system
        types: [python]
        require_serial: true
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black .
        language: system
        types: [python]
        require_serial: true
