---
# The hooks are run every time a ` git commit -m "blah" ` is run.
# Usage instructions: https://interrupt.memfault.com/blog/pre-commit#using-pre-commit

# exclude the click file b/c it can't be docstringed correctly
exclude: hello.py

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
- repo: https://github.com/PyCQA/pylint
  rev: v2.12.2
  hooks:
    - id: pylint
